#!/usr/bin/env bash

run_scenario() {
    log_step "Scenario 02: 'swiftblock new' with XcodeGen & Custom Prefix..."

    "$SWIFTBLOCK_BIN" new TestNewApp \
        --bundle-prefix com.mycompany.newapp \
        --template-path "$TEMPLATE_PATH" \
        --tool xcodegen

    assert_dir_exists "TestNewApp" "TestNewApp directory created by 'swiftblock new'"

    cd TestNewApp

    assert_file_exists "project.yml" "project.yml generated by XcodeGen"
    assert_file_contains "project.yml" "TestNewApp" "project.yml contains app name"
    assert_file_contains "project.yml" "com.mycompany.newapp" "project.yml contains bundle prefix"

    if which make > /dev/null 2>&1; then
        log_info "Testing real 'make setup' execution..."
        make setup
        log_success "'make setup' executed cleanly"
    fi

    cd "$TEST_DIR"
}

run_scenario
