import XCTest
@testable import __PROJECT_NAME__

final class __PROJECT_NAME__Tests: XCTestCase {

    func testExample() throws {
        // This is a sample unit test case generated by SwiftBlock.
        XCTAssertTrue(true)
    }
}
